type: object
required:
    - name
    - description
    - endpoint
properties:
    name:
        type: string
    description:
        type: string
    endpoint:
        type: string
        examples:
            - 'https://abc-bank.com'